### ISSUE TITLE
Do not read path to subderictories

### ISSUE THREAD

**Issue by Evreke** [tomgrooffer/gulp-sass-glob#1]
I have error using with path like that <pre>@import "***/**"; <br> Error: File to import not found or unreadable: d:/Work/PHPSTORM/gulp/app/modules/block_block.scss</pre>
My main.scss from wich i importing is in modules directory

**Comment by parhumm** [comment]
In Module folder do you have block folder?
and Do use windows?

**Comment by Evreke** [comment]
Answer on both questions is yes

**Comment by parhumm** [comment]
Look at Pull requests, I solved this bug with adding one line. :)

**Comment by tomgrooffer** [comment]
Thanks for all the feedback, I've updated the package and all pr's are merged.
