### ISSUE TITLE
Cannot read property toString of null

### ISSUE THREAD

**Issue by chrillewoodz** [tomgrooffer/gulp-sass-glob#17]
When I use [gulp-watch](https://www.npmjs.com/package/gulp-watch) and remove a SCSS file, gulp instantly breaks and and error is pointing to `node_modules/gulp-sass-glob/index.js:18` and this line: 

`var contents = file.contents.toString('utf-8');`

Is there a fix for this?

**Comment by CREEATION** [comment]
This is most likely not related to `gulp-sass-glob`, but `gulp-watch` (just a quick guess).

**Comment by tomgrooffer** [comment]
@chrillewoodz I could not recreate the error. I setup a project with gulp-watch, and tried to reproduce the error, but nothing happened. I hope you resolved the issue by yourself, if not, send me a message and I will help you out ;)

**Comment by core01** [comment]
I have the same error.
My gulpfile.js
`
var gulp = require('gulp');
var sass = require('gulp-sass');
var sassGlob = require('gulp-sass-glob');

gulp.task('css', function () {
    return gulp.src('assets/templates/sass/**/*')
        .pipe(sassGlob())
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('assets/templates/css'))
});
`

**Comment by heathdutton** [comment]
I'm getting this issue as well, not using watch either.
