### ISSUE TITLE
Add support for `includePaths`

### ISSUE THREAD

**Issue by Nirazul** [tomgrooffer/gulp-sass-glob#26]
`gulp-sass` has support for the `includePaths` option through `node-sass`. Refer to [the documentation](https://github.com/sass/node-sass#includepaths) for details.

Unfortunately there's no possibility for `gulp-sass-glob` to know about this. So it fails when handling globs from locations defined in there.

I think it would be straightforward for this plugin to add support for this feature.

**Comment by Apkawa** [comment]
#29

**Comment by nilssolanki** [comment]
Thank you for including this! Do you know when this is going to be released on npm?

**Comment by tomgrooffer** [comment]
@nilssolanki It is now live :) Thanks
