### ISSUE TITLE
Feature request for multiple single import with multiple lines

### ISSUE THREAD

**Issue by elliottmangham** [tomgrooffer/gulp-sass-glob#32]
Hello, 

It'd be awesome if gulp-sass-glob allowed you to do something like this (comma separated, and can be on multiple lines) like regular Sass:

`@import
    "mixins/*",
    "settings/*",
    "styleguide/*",
    "layout/*",
    "classes/*",
    "components/*",
    "pages/*"
;`

As it's much neater than having many @imports...

Kind regards

**Comment by Nirazul** [comment]
Doesn't this work?

```
@import "{mixins,settings,styleguide,layout,classes,components,pages}/*";
```

**Comment by tomgrooffer** [comment]
@elliottmangham Lets keep things as close to CSS as possible. This is not in the scope of this project.
