### ISSUE TITLE
Variables don't work on imported Sass files

### ISSUE THREAD

**Issue by elliottmangham** [tomgrooffer/gulp-sass-glob#33]
Hello,

I have all my imports set-up, the first one being 'variables.scss' where all my Sass variables are.

I them import all my other files which use the variables, but when I'm using gulp-sass-glob to import these files within the directories, it just errors, saying that the variable isn't defined.

Please help!

Kind regards

**Comment by tomgrooffer** [comment]
Please send me a PM and I will help you out. This is not an issue directly related to this project. Thanks
