### ISSUE TITLE
Exclude file?

### ISSUE THREAD

**Issue by jenstornell** [tomgrooffer/gulp-sass-glob#35]
Is it possible to exclude a file? I want the reset.scss to be called first. I can live with the fact that I need to call it with a special import rule first.

But then I want to exclude it from the search if possible? It now looks like this:

```scss
@import 'reset.scss';
@import '../../**/snippets/**/*'; // Exclude reset somehow?
```

**Comment by tomgrooffer** [comment]
I'm sorry I think you need to think differently with your project setup to prevent this kind of situation. Excluding is not in the scope of this project.

**Comment by jenstornell** [comment]
Thanks!

Maybe it's slow but I could probably use this to solve the problem:

https://www.npmjs.com/package/gulp-css-purge
