### ISSUE TITLE
Support globbing inside _partial file.

### ISSUE THREAD

**Issue by alexcracea** [tomgrooffer/gulp-sass-glob#36]
Hi,

I've spent a lot of time today trying to use a gulp sass globbing tool and finally found out that your package is awesome. 

However, my SCSS file structure is as follows:
SCSS
└──base
└──components
└──styles.scss
└──_styles-main.scss

In my styles.scss i only include
`
@charset 'UTF-8';
@import 'styles-main';
`

and including all the rest goes inside _styles-main.scss:
`//Base
@import 'base/*';
// Components
@import 'components/*';`

Problem is that "@import components/*" works only when I include it in the styles.scss and does not when i include it in _styles-main.scss.

Can this issue be solved?

**Comment by dsoldera** [comment]
Same problem

**Comment by DanielaValero** [comment]
I would imagine that it's possible, we would need to do some kind of recursion over the `transform` function here: https://github.com/tomgrooffer/gulp-sass-glob/blob/master/src/index.js#L16

@tomgrooffer what do you think?

**Comment by tomgrooffer** [comment]
@alexcracea @dsoldera @DanielaValero I'm very sorry for the late response but:

I have worked on a nested version on gulp-sass-glob but it's better to keep the project as simple as possible.

Feel free to experiment with the plugin and creating a PR for this functionality but I don't have any time soon for creating this.

I would like to point you to[ this part of the documentation](https://github.com/tomgrooffer/gulp-sass-glob#nested-glob-imports) which explains more about nested inclusions.

Again: sorry for the late response and I hope you understand my point of view ;)

**Comment by donquixote** [comment]
See #43
