### ISSUE TITLE
What order will the sass files be imported in? And is the order guaranteed? Please add to docs

### ISSUE THREAD

**Issue by JoshMoreno** [tomgrooffer/gulp-sass-glob#38]
First off, Thanks for making this, super useful!

Just like the title says. I didn't see any section in the docs mentioning the order of imports. Is it alphabetical, by file modification time, etc...

And further is the order guaranteed? Basically, can we rely on it?

Would be helpful addition to the docs.

**Comment by tomgrooffer** [comment]
@JoshMoreno Hi Josh, good question. The order is not guaranteed, it basically depends on the glob package that we use.

The best way to solve this problem is don't depend on the order.

I hope I answered your question enough, feel free to drop me a message otherwise.
