### ISSUE TITLE
the windows filepath replace has been merged out

### ISSUE THREAD

**Issue by parhumm** [tomgrooffer/gulp-sass-glob#8]
Hi, 
After new updates, old problem solved but generated file has lots of problem and sass codes compiled incorrectly.  I can't found problem can you help me?

Thanks

**Comment by tomgrooffer** [comment]
I have no windows PC, so its hard for me to test, can you provide some extra info about the problems in the compiled sass?

**Comment by tomgrooffer** [comment]
@parhumm should be fixed in new version (total rewrite), please update to 0.0.9 and check if issues still occur

**Comment by parhumm** [comment]
I will check it in next week. Thank you :)
