### ISSUE TITLE
Can't import in imported file.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [tomgrooffer/gulp-sass-glob#9]
Import files from directory works fine only in the root *.scss file.
When I try to import files from directory in the imported file - it gives and error.
```
@import "snippets/**/*.scss";
```

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: source/style/sections/admin/workers/_editor.scss
Error: File to import not found or unreadable: snippets/**/*.scss

```

But when I set specific file 
```
@import "snippets/element-item";
```
Everything works fine.

**Comment by tomgrooffer** [comment]
working on on it

**Comment by tomgrooffer** [comment]
@AlexanderKozhevin I think you should restructure your code man, this nested import globbing is pretty much out of scope of the project, maybe you can write a patch? I'm closing this now.

**Comment by Dan503** [comment]
:(

Being able to glob within an imported file would mean you can create little glob sets for easier code management.

It would have similar use cases to how gulp and grunt let you create tasks of just other tasks so you don't need to restate the same set of tasks all the time.
